// import { createOpenAI } from "@ai-sdk/openai";
import { createOpenAICompatible } from "@ai-sdk/openai-compatible";
import type { ProviderV2 } from "@ai-sdk/provider";
import { objectKeys } from "@travisennis/stdlib/object";
import { customProvider } from "ai";
import type { ModelMetadata } from "./providers.ts";

const openRouterClient = createOpenAICompatible({
  name: "openrouter",
  apiKey: process.env["OPENROUTER_API_KEY"] ?? "",
  // biome-ignore lint/style/useNamingConvention: third-party controlled
  baseURL: "https://openrouter.ai/api/v1",
  headers: {
    "HTTP-Referer": "https://github.com/travisennis/acai-ts",
    "X-Title": "acai",
  },
});

// const openRouterClient = createOpenAI({
//   // biome-ignore lint/style/useNamingConvention: third-party controlled
//   baseURL: "https://openrouter.ai/api/v1",
//   name: "openrouter",
//   apiKey: process.env["OPENROUTER_API_KEY"] ?? "",
//   headers: {
//     "HTTP-Referer": "https://github.com/travisennis/acai-ts",
//     "X-Title": "acai",
//   },
// });

const openrouterModels = {
  "claude-3-5-sonnet": openRouterClient("anthropic/claude-3.5-sonnet"),
  "deepseek-v3-2": openRouterClient("deepseek/deepseek-v3.2"),
  "gemini-3-pro": openRouterClient("google/gemini-3-pro-preview"),
  "glm-4-7": openRouterClient("z-ai/glm-4.7"),
  "kat-coder-pro-free": openRouterClient("kwaipilot/kat-coder-pro:free"),
  "minimax-m2-1": openRouterClient("minimax/minimax-m2.1"),
  "sonnet-4.5": openRouterClient("anthropic/claude-sonnet-4.5"),
  "opus-4.5": openRouterClient("anthropic/claude-opus-4.5"),
  "haiku-4.5": openRouterClient("anthropic/claude-haiku-4.5"),
  "kimi-k2": openRouterClient("moonshotai/kimi-k2-0905:exacto"),
  "kimi-k2-thinking": openRouterClient("moonshotai/kimi-k2-thinking"),
  "devstral-medium": openRouterClient("mistralai/devstral-medium"),
  "devstral-2512-free": openRouterClient("mistralai/devstral-2512:free"),
  "qwen3-coder": openRouterClient("qwen/qwen3-coder:exacto"),
  "qwen3-coder-plus": openRouterClient("qwen/qwen3-coder-plus"),
  "qwen3-max": openRouterClient("qwen/qwen3-max"),
  "glm-4.6": openRouterClient("z-ai/glm-4.6:exacto"),
  "gpt-oss-120b": openRouterClient("openai/gpt-oss-120b:exacto"),
  "grok-code-fast-1": openRouterClient("x-ai/grok-code-fast-1"),
  "grok-4-1-fast": openRouterClient("x-ai/grok-4.1-fast"),
  "gpt-5.1": openRouterClient("openai/gpt-5.1"),
  "gpt-5.1-codex": openRouterClient("openai/gpt-5.1-codex"),
  "gpt-5.1-codex-mini": openRouterClient("openai/gpt-5.1-codex-mini"),
  "gpt-5.1-codex-max": openRouterClient("openai/gpt-5.1-codex-max"),
  "gpt-5.2": openRouterClient("openai/gpt-5.2"),
  "gpt-5.2-codex": openRouterClient("openai/gpt-5.2-codex"),
  "minimax-m2": openRouterClient("minimax/minimax-m2"),
  "gemini-3-flash-preview": openRouterClient("google/gemini-3-flash-preview"),
} as const;

type ModelName = `openrouter:${keyof typeof openrouterModels}`;

export const openrouterModelNames: ModelName[] = objectKeys(
  openrouterModels,
).map((key) => `openrouter:${key}` as const);

export const openrouterProvider = {
  openrouter: customProvider({
    languageModels: openrouterModels,
    fallbackProvider: openRouterClient as unknown as ProviderV2,
  }),
};

export const openrouterModelRegistry: {
  [K in ModelName]: ModelMetadata<ModelName>;
} = {
  "openrouter:claude-3-5-sonnet": {
    id: "openrouter:claude-3-5-sonnet",
    provider: "openrouter",
    contextWindow: 200000,
    maxOutputTokens: 8192,
    defaultTemperature: 0.5,
    promptFormat: "markdown",
    supportsReasoning: false,
    supportsToolCalling: true,
    costPerInputToken: 0.000006,
    costPerOutputToken: 0.00003,
  },
  "openrouter:deepseek-v3-2": {
    id: "openrouter:deepseek-v3-2",
    provider: "openrouter",
    contextWindow: 163840,
    maxOutputTokens: 16000,
    defaultTemperature: 1.0,
    promptFormat: "bracket",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.00000027,
    costPerOutputToken: 0.0000004,
  },
  "openrouter:gemini-3-pro": {
    id: "openrouter:gemini-3-pro",
    provider: "openrouter",
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    defaultTemperature: 0.5,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.000002,
    costPerOutputToken: 0.000012,
  },
  "openrouter:glm-4-7": {
    id: "openrouter:glm-4-7",
    provider: "openrouter",
    contextWindow: 200000,
    maxOutputTokens: 131072,
    defaultTemperature: 0.5,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 1.1e-7,
    costPerOutputToken: 0.0000022,
  },
  "openrouter:kat-coder-pro-free": {
    id: "openrouter:kat-coder-pro-free",
    provider: "openrouter",
    contextWindow: 256000,
    maxOutputTokens: 32768,
    defaultTemperature: -1,
    promptFormat: "markdown",
    supportsReasoning: false,
    supportsToolCalling: true,
    costPerInputToken: 0,
    costPerOutputToken: 0,
  },
  "openrouter:minimax-m2-1": {
    id: "openrouter:minimax-m2-1",
    provider: "openrouter",
    contextWindow: 204800,
    maxOutputTokens: 131072,
    defaultTemperature: 0.5,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 3e-7,
    costPerOutputToken: 0.0000012,
  },
  "openrouter:opus-4.5": {
    id: "openrouter:opus-4.5",
    provider: "openrouter",
    contextWindow: 200000,
    maxOutputTokens: 32000,
    defaultTemperature: 1.0,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.000005,
    costPerOutputToken: 0.000025,
  },
  "openrouter:sonnet-4.5": {
    id: "openrouter:sonnet-4.5",
    provider: "openrouter",
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    defaultTemperature: 1.0,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.000003,
    costPerOutputToken: 0.000015,
  },
  "openrouter:kimi-k2": {
    id: "openrouter:kimi-k2",
    provider: "openrouter",
    contextWindow: 262144,
    maxOutputTokens: 8192,
    defaultTemperature: 0.6,
    promptFormat: "markdown",
    supportsReasoning: false,
    supportsToolCalling: true,
    costPerInputToken: 0.0000006,
    costPerOutputToken: 0.0000025,
  },
  "openrouter:kimi-k2-thinking": {
    id: "openrouter:kimi-k2-thinking",
    provider: "openrouter",
    contextWindow: 262144,
    maxOutputTokens: 8192,
    defaultTemperature: 0.6,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.0000006,
    costPerOutputToken: 0.0000025,
  },
  "openrouter:devstral-medium": {
    id: "openrouter:devstral-medium",
    provider: "openrouter",
    contextWindow: 131000,
    maxOutputTokens: 8192,
    defaultTemperature: 0.3,
    promptFormat: "markdown",
    supportsReasoning: false,
    supportsToolCalling: true,
    costPerInputToken: 0.0000004,
    costPerOutputToken: 0.000002,
  },
  "openrouter:devstral-2512-free": {
    id: "openrouter:devstral-2512-free",
    provider: "openrouter",
    contextWindow: 262144,
    maxOutputTokens: 32768,
    defaultTemperature: 0.3,
    promptFormat: "markdown",
    supportsReasoning: false,
    supportsToolCalling: true,
    costPerInputToken: 0,
    costPerOutputToken: 0,
  },
  "openrouter:qwen3-coder": {
    id: "openrouter:qwen3-coder",
    provider: "openrouter",
    contextWindow: 262000,
    maxOutputTokens: 66000,
    defaultTemperature: 0.55,
    promptFormat: "markdown",
    supportsReasoning: false,
    supportsToolCalling: true,
    costPerInputToken: 0.0000004,
    costPerOutputToken: 0.000002,
  },
  "openrouter:qwen3-coder-plus": {
    id: "openrouter:qwen3-coder-plus",
    provider: "openrouter",
    contextWindow: 128000,
    maxOutputTokens: 65536,
    defaultTemperature: 0.55,
    promptFormat: "markdown",
    supportsReasoning: false,
    supportsToolCalling: true,
    costPerInputToken: 0.000001,
    costPerOutputToken: 0.000005,
  },
  "openrouter:qwen3-max": {
    id: "openrouter:qwen3-max",
    provider: "openrouter",
    contextWindow: 256000,
    maxOutputTokens: 32768,
    defaultTemperature: 0.55,
    promptFormat: "markdown",
    supportsReasoning: false,
    supportsToolCalling: true,
    costPerInputToken: 0.0000012,
    costPerOutputToken: 0.000006,
  },
  "openrouter:glm-4.6": {
    id: "openrouter:glm-4.6",
    provider: "openrouter",
    contextWindow: 200000,
    maxOutputTokens: 128000,
    defaultTemperature: 0.6,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.0000006,
    costPerOutputToken: 0.0000022,
  },
  "openrouter:gpt-5.1": {
    id: "openrouter:gpt-5.1",
    provider: "openrouter",
    contextWindow: 400000,
    maxOutputTokens: 128000,
    defaultTemperature: 1.0,
    promptFormat: "xml",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.00000125,
    costPerOutputToken: 0.00001,
  },
  "openrouter:gpt-5.1-codex": {
    id: "openrouter:gpt-5.1-codex",
    provider: "openrouter",
    contextWindow: 400000,
    maxOutputTokens: 128000,
    defaultTemperature: -1,
    promptFormat: "xml",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.00000125,
    costPerOutputToken: 0.00001,
  },
  "openrouter:gpt-5.1-codex-mini": {
    id: "openrouter:gpt-5.1-codex-mini",
    provider: "openrouter",
    contextWindow: 400000,
    maxOutputTokens: 100000,
    defaultTemperature: -1,
    promptFormat: "xml",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.00000025,
    costPerOutputToken: 0.000002,
  },
  "openrouter:gpt-5.1-codex-max": {
    id: "openrouter:gpt-5.1-codex-max",
    provider: "openrouter",
    contextWindow: 400000,
    maxOutputTokens: 128000,
    defaultTemperature: -1,
    promptFormat: "xml",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.00000125,
    costPerOutputToken: 0.00001,
  },
  "openrouter:grok-code-fast-1": {
    id: "openrouter:grok-code-fast-1",
    provider: "openrouter",
    contextWindow: 256000,
    maxOutputTokens: 10000,
    defaultTemperature: 0.5,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.0000002,
    costPerOutputToken: 0.0000015,
  },
  "openrouter:gpt-oss-120b": {
    id: "openrouter:gpt-oss-120b",
    provider: "openrouter",
    contextWindow: 131072,
    maxOutputTokens: 64000,
    defaultTemperature: 1.0,
    promptFormat: "xml",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.00000007256312,
    costPerOutputToken: 0.0000002903936,
  },
  "openrouter:grok-4-1-fast": {
    id: "openrouter:grok-4-1-fast",
    provider: "openrouter",
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    defaultTemperature: 0.5,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.0000002,
    costPerOutputToken: 0.0000005,
  },
  "openrouter:haiku-4.5": {
    id: "openrouter:haiku-4.5",
    provider: "openrouter",
    contextWindow: 200000,
    maxOutputTokens: 32000,
    defaultTemperature: 1.0,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.000001,
    costPerOutputToken: 0.000005,
  },
  "openrouter:gpt-5.2": {
    id: "openrouter:gpt-5.2",
    provider: "openrouter",
    contextWindow: 400000,
    maxOutputTokens: 128000,
    defaultTemperature: 1.0,
    promptFormat: "xml",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.00000175,
    costPerOutputToken: 0.000014,
  },
  "openrouter:gpt-5.2-codex": {
    id: "openrouter:gpt-5.2-codex",
    provider: "openrouter",
    contextWindow: 400000,
    maxOutputTokens: 128000,
    defaultTemperature: -1,
    promptFormat: "xml",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.00000175,
    costPerOutputToken: 0.000014,
  },
  "openrouter:minimax-m2": {
    id: "openrouter:minimax-m2",
    provider: "openrouter",
    contextWindow: 196608,
    maxOutputTokens: 32768,
    defaultTemperature: 0.6,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.00000015,
    costPerOutputToken: 0.00000045,
  },
  "openrouter:gemini-3-flash-preview": {
    id: "openrouter:gemini-3-flash-preview",
    provider: "openrouter",
    contextWindow: 1048576,
    maxOutputTokens: 65535,
    defaultTemperature: 0.5,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.0000005,
    costPerOutputToken: 0.000003,
  },
};
