// import { createOpenAI } from "@ai-sdk/openai";
import { createOpenAICompatible } from "@ai-sdk/openai-compatible";
import type { ProviderV2 } from "@ai-sdk/provider";
import { objectKeys } from "@travisennis/stdlib/object";
import { customProvider } from "ai";
import type { ModelMetadata } from "./providers.ts";

const openRouterClient = createOpenAICompatible({
  name: "openrouter",
  apiKey: process.env["OPENROUTER_API_KEY"] ?? "",
  // biome-ignore lint/style/useNamingConvention: third-party controlled
  baseURL: "https://openrouter.ai/api/v1",
  headers: {
    "HTTP-Referer": "https://github.com/travisennis/acai-ts",
    "X-Title": "acai",
  },
});

// const openRouterClient = createOpenAI({
//   // biome-ignore lint/style/useNamingConvention: third-party controlled
//   baseURL: "https://openrouter.ai/api/v1",
//   name: "openrouter",
//   apiKey: process.env["OPENROUTER_API_KEY"] ?? "",
//   headers: {
//     "HTTP-Referer": "https://github.com/travisennis/acai-ts",
//     "X-Title": "acai",
//   },
// });

const openrouterModels = {
  "deepseek-v3-2": openRouterClient("deepseek/deepseek-v3.2"),
  "glm-4-7": openRouterClient("z-ai/glm-4.7"),
  "glm-4-7-flash": openRouterClient("z-ai/glm-4.7-flash"),
  "minimax-m2-5": openRouterClient("minimax/minimax-m2.5"),
  "sonnet-4.5": openRouterClient("anthropic/claude-sonnet-4.5"),
  "opus-4.6": openRouterClient("anthropic/claude-opus-4.6"),
  "haiku-4.5": openRouterClient("anthropic/claude-haiku-4.5"),
  "kimi-k2-5": openRouterClient("moonshotai/kimi-k2.5"),
  "qwen3-max": openRouterClient("qwen/qwen3-max"),
  "qwen3-max-thinking": openRouterClient("qwen/qwen3-max-thinking"),
  "qwen3-coder-next": openRouterClient("qwen/qwen3-coder-next"),
  "glm-5": openRouterClient("z-ai/glm-5"),
  "gpt-oss-120b": openRouterClient("openai/gpt-oss-120b:exacto"),
  "grok-code-fast-1": openRouterClient("x-ai/grok-code-fast-1"),
  "grok-4-1-fast": openRouterClient("x-ai/grok-4.1-fast"),
  "gpt-5.1-codex-mini": openRouterClient("openai/gpt-5.1-codex-mini"),
  "gpt-5.1-codex-max": openRouterClient("openai/gpt-5.1-codex-max"),
  "gpt-5.2": openRouterClient("openai/gpt-5.2"),
  "gpt-5.2-codex": openRouterClient("openai/gpt-5.2-codex"),
} as const;

type ModelName = `openrouter:${keyof typeof openrouterModels}`;

export const openrouterModelNames: ModelName[] = objectKeys(
  openrouterModels,
).map((key) => `openrouter:${key}` as const);

export const openrouterProvider = {
  openrouter: customProvider({
    languageModels: openrouterModels,
    fallbackProvider: openRouterClient as unknown as ProviderV2,
  }),
};

export const openrouterModelRegistry: {
  [K in ModelName]: ModelMetadata<ModelName>;
} = {
  "openrouter:deepseek-v3-2": {
    id: "openrouter:deepseek-v3-2",
    provider: "openrouter",
    contextWindow: 163840,
    maxOutputTokens: 16000,
    defaultTemperature: 1.0,
    promptFormat: "bracket",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.00000027,
    costPerOutputToken: 0.0000004,
  },
  "openrouter:glm-4-7": {
    id: "openrouter:glm-4-7",
    provider: "openrouter",
    contextWindow: 200000,
    maxOutputTokens: 131072,
    defaultTemperature: 0.5,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 1.1e-7,
    costPerOutputToken: 0.0000022,
  },
  "openrouter:glm-4-7-flash": {
    id: "openrouter:glm-4-7-flash",
    provider: "openrouter",
    contextWindow: 200000,
    maxOutputTokens: 131072,
    defaultTemperature: 0.5,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 7e-8,
    costPerOutputToken: 4e-7,
  },
  "openrouter:minimax-m2-5": {
    id: "openrouter:minimax-m2-5",
    provider: "openrouter",
    contextWindow: 204800,
    maxOutputTokens: 131072,
    defaultTemperature: 0.5,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 3e-7,
    costPerOutputToken: 0.0000012,
  },
  "openrouter:opus-4.6": {
    id: "openrouter:opus-4.6",
    provider: "openrouter",
    contextWindow: 200000,
    maxOutputTokens: 32000,
    defaultTemperature: 1.0,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.000005,
    costPerOutputToken: 0.000025,
  },
  "openrouter:sonnet-4.5": {
    id: "openrouter:sonnet-4.5",
    provider: "openrouter",
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    defaultTemperature: 1.0,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.000003,
    costPerOutputToken: 0.000015,
  },
  "openrouter:kimi-k2-5": {
    id: "openrouter:kimi-k2-5",
    provider: "openrouter",
    contextWindow: 262144,
    maxOutputTokens: 262144,
    defaultTemperature: 1.0,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 6e-7,
    costPerOutputToken: 0.000003,
  },
  "openrouter:qwen3-max": {
    id: "openrouter:qwen3-max",
    provider: "openrouter",
    contextWindow: 256000,
    maxOutputTokens: 32768,
    defaultTemperature: 0.55,
    promptFormat: "markdown",
    supportsReasoning: false,
    supportsToolCalling: true,
    costPerInputToken: 0.0000012,
    costPerOutputToken: 0.000006,
  },
  "openrouter:qwen3-max-thinking": {
    id: "openrouter:qwen3-max-thinking",
    provider: "openrouter",
    contextWindow: 262144,
    maxOutputTokens: 65536,
    defaultTemperature: 0.5,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.0000012,
    costPerOutputToken: 0.000006,
  },
  "openrouter:glm-5": {
    id: "openrouter:glm-5",
    provider: "openrouter",
    contextWindow: 204800,
    maxOutputTokens: 64800,
    defaultTemperature: 0.5,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.000001,
    costPerOutputToken: 0.0000032,
  },
  "openrouter:qwen3-coder-next": {
    id: "openrouter:qwen3-coder-next",
    provider: "openrouter",
    contextWindow: 262144,
    maxOutputTokens: 65536,
    defaultTemperature: -1,
    promptFormat: "markdown",
    supportsReasoning: false,
    supportsToolCalling: true,
    costPerInputToken: 0.00000007,
    costPerOutputToken: 0.0000003,
  },
  "openrouter:gpt-5.1-codex-mini": {
    id: "openrouter:gpt-5.1-codex-mini",
    provider: "openrouter",
    contextWindow: 400000,
    maxOutputTokens: 100000,
    defaultTemperature: -1,
    promptFormat: "xml",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.00000025,
    costPerOutputToken: 0.000002,
  },
  "openrouter:gpt-5.1-codex-max": {
    id: "openrouter:gpt-5.1-codex-max",
    provider: "openrouter",
    contextWindow: 400000,
    maxOutputTokens: 128000,
    defaultTemperature: -1,
    promptFormat: "xml",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.00000125,
    costPerOutputToken: 0.00001,
  },
  "openrouter:grok-code-fast-1": {
    id: "openrouter:grok-code-fast-1",
    provider: "openrouter",
    contextWindow: 256000,
    maxOutputTokens: 10000,
    defaultTemperature: 0.5,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.0000002,
    costPerOutputToken: 0.0000015,
  },
  "openrouter:gpt-oss-120b": {
    id: "openrouter:gpt-oss-120b",
    provider: "openrouter",
    contextWindow: 131072,
    maxOutputTokens: 64000,
    defaultTemperature: 1.0,
    promptFormat: "xml",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.00000007256312,
    costPerOutputToken: 0.0000002903936,
  },
  "openrouter:grok-4-1-fast": {
    id: "openrouter:grok-4-1-fast",
    provider: "openrouter",
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    defaultTemperature: 0.5,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.0000002,
    costPerOutputToken: 0.0000005,
  },
  "openrouter:haiku-4.5": {
    id: "openrouter:haiku-4.5",
    provider: "openrouter",
    contextWindow: 200000,
    maxOutputTokens: 32000,
    defaultTemperature: 1.0,
    promptFormat: "markdown",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.000001,
    costPerOutputToken: 0.000005,
  },
  "openrouter:gpt-5.2": {
    id: "openrouter:gpt-5.2",
    provider: "openrouter",
    contextWindow: 400000,
    maxOutputTokens: 128000,
    defaultTemperature: 1.0,
    promptFormat: "xml",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.00000175,
    costPerOutputToken: 0.000014,
  },
  "openrouter:gpt-5.2-codex": {
    id: "openrouter:gpt-5.2-codex",
    provider: "openrouter",
    contextWindow: 400000,
    maxOutputTokens: 128000,
    defaultTemperature: -1,
    promptFormat: "xml",
    supportsReasoning: true,
    supportsToolCalling: true,
    costPerInputToken: 0.00000175,
    costPerOutputToken: 0.000014,
  },
};
